create_thrift_libraries(
    base_name = "thrift",
    sources = rglobs("*.thrift"),
    generate_languages = [
        "go",
        "java",
        "lua",
        "python",
        "ruby",
        "scala",
        "strato",
    ],
    provides_java_name = "finatra-thrift-java",
    provides_scala_name = "finatra-thrift-scala",
)
