create_thrift_libraries(
  base_name='thrift',
  sources=globs('*.thrift'),
  generate_languages=["scala"],
  provides_java_name='finatra-thrift-java',
  provides_scala_name='finatra-thrift-scala',
)
