target(
    tags = [
        # users should depend on specific finer-grained targets instead of this monolithic target
        "deprecated",
    ],
    dependencies = [
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson",
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson/caseclass",
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson/caseclass/exceptions",
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson/modules",
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson/serde",
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson/streaming",
        "finatra/jackson/src/main/scala/com/twitter/finatra/json",
        "finatra/jackson/src/main/scala/com/twitter/finatra/json/utils",
    ],
)
