java_library(
    sources = ["*.java"],
    compiler_option_sets = {},
    provides = artifact(
        org = "com.twitter",
        name = "finatra-http-java-jsonpatch",
        repo = artifactory,
    ),
    strict_deps = "True",
)
