target(
    tags = ["bazel-compatible"],
    dependencies = [
        "finatra/inject/inject-app/src/main/java/com/twitter/inject/annotations",
        "finatra/inject/inject-app/src/main/scala/com/twitter/inject/app",
    ],
)
