create_thrift_libraries(
    base_name = "thrift",
    sources = rglobs("*.thrift"),
    dependency_roots = [
        "finatra/thrift/src/main/thrift:thrift",
    ],
    provides_java_name = "calculator-thrift-java",
)
