target(name='inject-modules',
  dependencies=[
    'finatra/inject/inject-modules/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/inject/inject-modules/src/test/scala'
  ]
)

target(name='test-deps',
  dependencies=[
    'finatra/inject/inject-modules/src/test/scala:test-deps'
  ]
)
