junit_tests(
    sources = rglobs("*.java"),
    compiler_option_sets = {},
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/slf4j:slf4j-simple",
        "finatra/examples/java-server/src/main/java",
        "finatra/inject/inject-app/src/main/scala",
        "finatra/inject/inject-app/src/test/scala:test-deps",
        "finatra/inject/inject-server/src/main/scala",
        "finatra/inject/inject-server/src/test/scala:test-deps",
        "twitter-server/server/src/main/scala",
    ],
)
