#!/bin/sh
# Usage: finatra update-readme
# Summary: generates the README.markdown from the template

set -e

source $_FINATRA_ROOT/lib/base.sh

cp README.markdown.template README.markdown
sed -ie "s/###VERSION###/$VERSION/g" README.markdown
rm -rf README.markdowne
