#!/bin/sh
# Usage: finatra update-readme
# Summary: generates the README.markdown from the template

set -e

source $_FINATRA_ROOT/lib/base.sh

cp README.markdown.template README.markdown
replace_with_example_app README.markdown
replace_with_example_spec README.markdown
rm -rf README.markdowne
