maven_layout()

target(name='inject-app',
  dependencies=[
    'inject/inject-app/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'inject/inject-app/src/test/scala'
  ]
)

target(name='test-deps',
  dependencies=[
    'inject/inject-app/src/test/scala:test-deps'
  ]
)
