create_thrift_libraries(
    base_name = "thrift",
    sources = rglobs("*.thrift"),
    dependency_roots = [
    ],
    generate_languages = [
        "java",
        "scala",
    ],
    provides_java_name = "kafka-streams-thrift-java",
    provides_scala_name = "kafka-streams-thrift-scala",
)
