target(
    name = "test-deps",
    tags = {
        # users should prefer finatra/inject/inject-server/src/test/scala/com/twitter/inject/server directly
        "deprecated",
    },
    dependencies = [
        "finatra/inject/inject-server/src/test/scala/com/twitter/inject/server",
    ],
)
