target(
    name = "test-deps",
    tags = [
        "bazel-compatible",
        # users should prefer finatra/inject/inject-server/src/test/scala/com/twitter/inject/server directly
        "deprecated",
    ],
    dependencies = [
        "finatra/inject/inject-server/src/test/scala/com/twitter/inject/server",
    ],
)
