target(name='thrift',
  dependencies=[
    'finatra/thrift/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/thrift/src/test/scala'
  ]
)

target(name='test-deps',
  dependencies=[
    'finatra/thrift/src/test/scala:test-deps'
  ]
)
