target(
    name = "test-deps",
    tags = [
        # please use finatra/thrift/src/main/test/com/twitter/finatra/thrift directly
        "deprecated",
    ],
    dependencies = [
        "finatra/thrift/src/test/scala/com/twitter/finatra/thrift",
    ],
)
