target(
    dependencies = [
        "finatra/inject-thrift-client-http-mapper/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "finatra/inject-thrift-client-http-mapper/src/test/scala",
    ],
)
