target(name='inject-thrift-client-http-mapper',
  dependencies=[
    'finatra/inject-thrift-client-http-mapper/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/inject-thrift-client-http-mapper/src/test/scala'
  ]
)
