target(name='inject-thrift-client',
  dependencies=[
    'finatra/inject/inject-thrift-client/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/inject/inject-thrift-client/src/test/scala'
  ]
)
