target(
    name = "test-deps",
    tags = [
        "bazel-compatible",
        # please use finatra/http-server/src/test/scala/com/twitter/finatra/http directly
        "deprecated",
    ],
    dependencies = [
        "finatra/http-server/src/test/scala/com/twitter/finatra/http",
    ],
)
