target(
    dependencies = [
        "finatra/httpclient/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "finatra/httpclient/src/test/scala",
    ],
)

target(
    name = "test-deps",
    dependencies = [
        "finatra/httpclient/src/test/scala:test-deps",
    ],
)
