maven_layout()

target(name='httpclient',
  dependencies=[
    'httpclient/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'httpclient/src/test/scala'
  ]
)

target(name='test-deps',
  dependencies=[
    'httpclient/src/test/scala:test-deps'
  ]
)
