junit_tests(
    sources = ["com/twitter/hello/server/*.java"],
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/slf4j:slf4j-simple",
        "finagle/finagle-base-http/src/main",
        "finatra/examples/java-http-server/src/main/java",
        "finatra/http/src/test/scala/com/twitter/finatra/http",
        "finatra/httpclient/src/main/scala",
        "finatra/inject/inject-app/src/main/scala",
        "finatra/inject/inject-server/src/main/scala",
        "twitter-server/server/src/main/scala",
    ],
)
