target(name='inject-utils',
  dependencies=[
    'finatra/inject/inject-utils/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/inject/inject-utils/src/test/scala'
  ]
)

target(name='test-deps',
  dependencies=[
    'finatra/inject/inject-utils/src/test/scala:test-deps'
  ]
)
