java_library(
    sources = ["**/*.java"],
    compiler_option_sets = {},
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/com/google/inject/extensions:guice-assistedinject",
        "3rdparty/jvm/com/google/inject/extensions:guice-multibindings",
        "3rdparty/jvm/net/codingwell:scala-guice",
        "finatra/examples/java-server/src/main/resources",
        "finatra/inject/inject-app/src/main/scala",
        "finatra/inject/inject-core/src/main/scala",
        "finatra/inject/inject-modules/src/main/scala",
        "finatra/inject/inject-server/src/main/scala",
        "twitter-server/server/src/main/scala",
    ],
)
