maven_layout()

target(name='finatra-scopes',
  dependencies=[
    'finatra/finatra/finatra-scopes/src/main/scala',
  ]
)

target(name='tests',
  dependencies=[
    'finatra/finatra/finatra-scopes/src/test/scala'
  ]
)
