java_library(
    sources = globs("*.java"),
    compiler_option_sets = {},
    provides = artifact(
        org = "com.twitter",
        name = "finatra-http-java-annotations",
        repo = artifactory,
    ),
    strict_deps = True,
)
