target(
    name = "test-deps",
    tags = {
        # users should depend on more fine-grained targets directly
        "deprecated",
    },
    dependencies = [
        "finatra/utils/src/test/scala/com/twitter/finatra/modules",
        "finatra/utils/src/test/scala/com/twitter/finatra/test",
    ],
)
