target(name='http',
  dependencies=[
    'finatra/http/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/http/src/test/scala'
  ]
)

target(name='test-deps',
  dependencies=[
    'finatra/http/src/test/scala:test-deps'
  ]
)
