target(name='jackson',
  dependencies=[
    'finatra/jackson/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/jackson/src/test/scala'
  ]
)

target(name='test-deps',
  dependencies=[
    'finatra/jackson/src/test/scala:test-deps'
  ]
)
