create_thrift_libraries(
    base_name = "doeverything-thrift",
    sources = ["*.thrift"],
    tags = ["bazel-compatible"],
    generate_languages = [
        "java",
        "scala",
    ],
    provides_java_name = "doeverything-thrift-java",
    provides_scala_name = "doeverything-thrift-scala",
)
