target(
    name = "tests",
    dependencies = [
        "finatra/inject/inject-app/src/test/scala/com/twitter/inject/app/tests",
        "finatra/inject/inject-core:tests",
        "finatra/inject/inject-modules:tests",
        "finatra/inject/inject-request-scope:tests",
        "finatra/inject/inject-server/src/test/scala/com/twitter/inject/server/tests",
        "finatra/inject/inject-server/src/test/scala/com/twitter/server/tests",
        "finatra/inject/inject-thrift-client:tests",
        "finatra/inject/inject-utils:tests",
    ],
)
