maven_layout()

target(name='finatra-logback',
  dependencies=[
    'finatra/finatra/finatra-logback/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/finatra/finatra-logback/src/test/scala'
  ]
)
