junit_tests(
    sources = ["*.scala"],
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "finatra/inject/inject-core/src/test/scala:test-deps",
        "finatra/inject/inject-server/src/main/scala/com/twitter/server/internal",
    ],
)
