create_thrift_libraries(
    base_name = "thrift",
    sources = globs("*.thrift"),
    dependency_roots = [
        "finatra/thrift/src/main/thrift:thrift",
    ],
    generate_languages = ["scala"],
)
