scala_library(
    compiler_option_sets = ["fatal_warnings"],
    provides = scala_artifact(
        org = "com.twitter",
        name = "finatra-http-core-request",
        repo = artifactory,
    ),
    dependencies = [
        "finagle/finagle-core/src/main",
        "finagle/finagle-http/src/main/scala",
        "util/util-core:scala",
    ],
)
