target(
    tags = [
        "bazel-compatible",
        # users should prefer to depend on finatra/inject/inject-slf4j/src/main/scala/com/twitter/inject
        "deprecated",
    ],
    dependencies = [
        "finatra/inject/inject-slf4j/src/main/scala/com/twitter/inject",
    ],
)
