target(
    tags = [
        "bazel-compatible",
        # users should prefer to depend on util/util-slf4j-api/src/main/scala/com/twitter/util/logging
        "deprecated",
    ],
    dependencies = [
        "finatra/inject/inject-slf4j/src/main/scala/com/twitter/inject",
    ],
)
