java_library(
    sources = ["*.java"],
    compiler_option_sets = [],
    platform = "java8",
    provides = artifact(
        org = "com.twitter",
        name = "finatra-http-java-core",
        repo = artifactory,
    ),
    strict_deps = True,
    tags = ["bazel-compatible"],
)
