junit_tests(name='scala',
  dependencies=[
    'finatra/inject/inject-core:test-deps',
    'finatra/inject/inject-thrift',
  ],
  fatal_warnings=True,
  sources=rglobs('com/twitter/inject/tests/exceptions/*.scala'),
)