target(
    tags = [
        "bazel-compatible",
        # users should depend on specific finer-grained targets instead of this monolithic target
        "deprecated",
    ],
    dependencies = [
        "finatra/inject/inject-core/src/main/scala/com/twitter/inject",
    ],
)
