java_library(
    sources = ["**/*.java"],
    compiler_option_sets = [],
    provides = artifact(
        org = "com.twitter",
        name = "finatra-kafka-java",
        repo = artifactory,
    ),
    strict_deps = True,
    dependencies = [
    ],
    exports = [
    ],
)
