java_library(
    sources = rglobs("*.java"),
    compiler_option_sets = {},
    provides = artifact(
        org = "com.twitter",
        name = "finatra-kafka-java",
        repo = artifactory,
    ),
    dependencies = [
    ],
    exports = [
    ],
)
