java_library(
    sources = rglobs("*.java"),
    compiler_option_sets = {},
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "finatra/jackson/src/main/scala",
    ],
    exports = [
        "3rdparty/jvm/com/google/inject:guice",
        "finatra/jackson/src/main/scala",
    ],
)
