target(name='finatra-examples',
  dependencies=[
    'finatra/finatra/finatra-examples/finatra-hello-world'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/finatra/finatra-examples/finatra-hello-world:tests',
  ]
)
