target(name='finatra-examples',
  dependencies=[
    'finatra/finatra/finatra-examples/finatra-twitter-example'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/finatra/finatra-examples/finatra-twitter-example:tests',
  ]
)
