maven_layout()

target(name='inject-core',
  dependencies=[
    'inject/inject-core/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'inject/inject-core/src/test/scala'
  ]
)

target(name='test-deps',
  dependencies=[
    'inject/inject-core/src/test/scala:test-deps'
  ]
)
