java_library(name='java',
  provides = artifact(
    org = 'com.twitter.finatra',
    name = 'finatra-scopes-java',
    repo = artifactory,
  ),
  dependencies=[
    '3rdparty/jvm/com/google/inject:guice',
  ],
  sources=rglobs('*.java'),
)
