java_library(name='java',
  provides = artifact(
    org = 'com.twitter.inject',
    name = 'inject-request-scope-java',
    repo = artifactory,
  ),
  dependencies=[
    '3rdparty/jvm/com/google/inject:guice',
  ],
  sources=rglobs('*.java'),
)
