target(
    name = "test-deps",
    tags = [
        "bazel-compatible",
        # users should prefer to depend on finatra/inject/inject-core/src/test/scala/com/twitter/inject
        "deprecated",
    ],
    dependencies = [
        "finatra/inject/inject-core/src/test/scala/com/twitter/inject",
    ],
)
