junit_tests(
  name='scala',
  dependencies=[
    '3rdparty:junit',
    '3rdparty:scalatest',
    '3rdparty:specs2',
    'finatra/finatra/finatra-examples/finatra-hello-world',
    'finatra/finatra/finatra-http:tests',
    'finatra/finatra/finatra-server:tests'
  ],
  sources=rglobs('*.scala'),
  resources=[
    'finatra/finatra/finatra-examples/finatra-hello-world/src/test/resources'
  ]
)

