jvm_binary(
    name = "bin",
    basename = "web-dashboard",
    main = "com.twitter.web.dashboard.ServerMain",
    tags = ["bazel-compatible"],
    dependencies = [
        "finatra/examples/advanced/web-dashboard/src/main/scala",
        "twitter-server/logback-classic/src/main/scala",
    ],
)
