target(name='examples',
  dependencies=[
    'examples/finatra-hello-world',
    'examples/finatra-twitter-clone'
  ]
)

target(name='tests',
  dependencies=[
    'examples/finatra-hello-world:tests',
    'examples/finatra-twitter-clone:tests'
  ]
)
