target(name='examples',
  dependencies=[
    'finatra/examples/finatra-hello-world',
    'finatra/examples/finatra-hello-world-heroku',
    'finatra/examples/finatra-twitter-clone'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/examples/finatra-hello-world:tests',
    'finatra/examples/finatra-hello-world-heroku:tests',
    'finatra/examples/finatra-twitter-clone:tests'
  ]
)
