java_library(name='java',
  provides = artifact(
    org = 'com.twitter.finatra',
    name = 'finatra-http-java',
    repo = artifactory,
  ),
  dependencies=[
    '3rdparty:guice'
  ],
  sources=rglobs('*.java')
)
