maven_layout()

target(name='finatra-httpclient',
  dependencies=[
    'finatra/finatra/finatra-httpclient/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/finatra/finatra-httpclient/src/test/scala'
  ]
)

target(name='test-deps',
  dependencies=[
    'finatra/finatra/finatra-httpclient/src/test/scala:test-deps'
  ]
)