target(
    name = "test-deps",
    tags = {
        # please use finatra/http/src/test/scala/com/twitter/finatra/http directly
        "deprecated",
    },
    dependencies = [
        "finatra/http/src/test/scala/com/twitter/finatra/http",
    ],
)
