target(
    dependencies = [
        "finatra/inject/inject-server/src/main/scala",
    ],
)

target(
    name = "tests",
    dependencies = [
        "finatra/inject/inject-server/src/test/scala",
    ],
)

target(
    name = "test-deps",
    dependencies = [
        "finatra/inject/inject-server/src/test/scala:test-deps",
    ],
)
