target(name='inject-request-scope',
  dependencies=[
    'finatra/inject/inject-request-scope/src/main/scala',
  ]
)

target(name='tests',
  dependencies=[
    'finatra/inject/inject-request-scope/src/test/scala'
  ]
)
