target(
    dependencies = [
        "finatra/inject/inject-thrift/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "finatra/inject/inject-thrift/src/test/scala",
    ],
)
