junit_tests(
    sources = [
        "*.java",
        "*.scala",
        "constraints/*.scala",
    ],
    strict_deps = True,
    dependencies = [
        "3rdparty/jvm/org/joda:joda-convert",
        "3rdparty/jvm/org/scalacheck",
        "3rdparty/jvm/org/scalatest",
        "finatra/inject/inject-core/src/test/scala:test-deps",
        "finatra/inject/inject-slf4j/src/main/scala",
        "finatra/validation/src/main/java/com/twitter/finatra/validation",
        "finatra/validation/src/main/scala/com/twitter/finatra/validation",
        "finatra/validation/src/test/scala/com/twitter/finatra/validation",
    ],
)
