target(name='utils',
  dependencies=[
    'finatra/utils/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/utils/src/test/scala'
  ]
)

target(name='test-deps',
  dependencies=[
    'finatra/utils/src/test/scala:test-deps'
  ]
)
