java_library(
    sources = globs("*.java"),
    compiler_option_sets = {"fatal_warnings"},
    strict_deps = "True",
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "finatra/json-annotations/src/main/java/com/twitter/finatra/json/annotations",
    ],
)
