junit_tests(
    sources = ["*.java"],
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scalatestplus:junit",
        "finatra/inject/inject-slf4j/src/main/scala/com/twitter/inject",
        "finatra/validation/src/main/scala/com/twitter/finatra/validation",
        "finatra/validation/src/test/scala/com/twitter/finatra/validation/tests",
    ],
)
