java_library(
    sources = rglobs(
        "com/twitter/finatra/kafkastreams/*.java",
    ),
    compiler_option_sets = {},
    provides = artifact(
        org = "com.twitter",
        name = "finatra-streams-java",
        repo = artifactory,
    ),
    strict_deps = True,
    dependencies = [],
)
