junit_tests(
    sources = ["*.scala"],
    dependencies = [
        "3rdparty/jvm/com/fasterxml/jackson/core:jackson-annotations",
        "3rdparty/jvm/org/scalatest",
        "3rdparty/jvm/org/scalatestplus:junit",
        "3rdparty/jvm/org/slf4j:slf4j-simple",
        "finatra/inject/inject-core/src/test/scala/com/twitter/inject",
        "finatra/jackson/src/main/scala/com/twitter/finatra/json",
        "finatra/jackson/src/test/java/com/twitter/finatra/jackson",
    ],
)
