junit_tests(
    sources = ["*.scala"],
    dependencies = [
        "3rdparty/jvm/com/fasterxml/jackson/core:jackson-databind",
        "3rdparty/jvm/org/scalatest",
        "finatra/inject/inject-app/src/test/scala:test-deps",
        "finatra/inject/inject-core/src/test/scala:test-deps",
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson",
        "finatra/jackson/src/main/scala/com/twitter/finatra/json",
        "finatra/jackson/src/main/scala/com/twitter/finatra/json/utils",
        "finatra/jackson/src/test/java/com/twitter/finatra/jackson",
        "finatra/jackson/src/test/scala/com/twitter/finatra/jackson/tests",
        "finatra/jackson/src/test/scala/com/twitter/finatra/json",
    ],
)
