java_library(
    sources = ["**/*.java"],
    compiler_option_sets = {},
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "finagle/finagle-base-http/src/main/scala",
        "finagle/finagle-core/src/main/scala",
        "finatra/examples/java-http-server/src/main/resources",
        "finatra/http/src/main/java",
        "finatra/http/src/main/scala",
        "finatra/inject/inject-app/src/main/scala",
        "finatra/inject/inject-core/src/main/scala",
        "finatra/inject/inject-server/src/main/scala",
        "twitter-server/server/src/main/scala",
        "util/util-app/src/main/scala",
    ],
)
