target(
    tags = {
        # users should depend on specific finer-grained targets instead of this monolithic target
        "deprecated",
    },
    dependencies = [
        "finatra/inject/inject-modules/src/main/scala/com/twitter/inject/modules",
    ],
)
