maven_layout()

target(name='finatra-http',
  dependencies=[
    'finatra/finatra/finatra-http/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'finatra/finatra/finatra-http/src/test/scala'
  ]
)

target(name='test-deps',
  dependencies=[
    'finatra/finatra/finatra-http/src/test/scala:test-deps'
  ]
)
