junit_tests(
    sources = ["**/*.java"],
    compiler_option_sets = {},
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/slf4j:slf4j-simple",
        "finagle/finagle-thrift/src/main/scala",
        "finatra/examples/java-thrift-server/thrift-example-server/src/main/java",
        "finatra/examples/thrift-server/thrift-example-idl/src/main/thrift:thrift-java",
        "finatra/inject/inject-server/src/main/scala",
        "finatra/inject/inject-server/src/test/scala:test-deps",
        "finatra/thrift/src/main/scala",
        "finatra/thrift/src/test/scala:test-deps",
        "twitter-server/server/src/main/scala",
    ],
)
