junit_tests(
    tags = ["bazel-compatible"],
    dependencies = [
        "finagle/finagle-core/src/main",
        "finagle/finagle-http/src/main/scala",
        "finatra/http-core/src/main/scala/com/twitter/finatra/http/response",
        "finatra/http-core/src/main/scala/com/twitter/finatra/http/streaming",
        "finatra/inject/inject-core/src/main/scala",
        "finatra/inject/inject-core/src/test/scala/com/twitter/inject",
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson/streaming",
        "util/util-core:scala",
        "util/util-jackson/src/main/scala/com/twitter/util/jackson",
        "util/util-mock/src/main/scala/com/twitter/util/mock",
    ],
)
