junit_tests(
    dependencies = [
        "finagle/finagle-core/src/main",
        "finagle/finagle-http/src/main/scala",
        "finatra/http-core/src/main/scala/com/twitter/finatra/http/streaming",
        "finatra/inject/inject-core/src/main/scala",
        "finatra/inject/inject-core/src/test/scala/com/twitter/inject",
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson",
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson/streaming",
        "util/util-core:scala",
    ],
)
