junit_tests(
    sources = rglobs(
        "*.java",
    ),
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/junit",
        "finatra/inject/inject-app/src/test/scala:test-deps",
        "finatra/inject/inject-core/src/main/scala/com/twitter/inject",
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson",
        "finatra/jackson/src/main/scala/com/twitter/finatra/jackson/modules",
    ],
)
